### PR TITLE
New page UI Enhance

### PR DESCRIPTION
**Pull request by raghav1482**
## Related Issue #1434 

Closes: #issue_number

## Screenshots

Screenshot 2024-01-11 130657

## Checklist 

- [ x] My code adheres to the established style guidelines of the project.
- [ x] I have included comments in areas that may be difficult to understand.
- [ x] My changes have not introduced any new warnings.
- [ x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by raghav1482** [comment]
@akshitagupta15june   Kindly review my PR #1450

**Comment by akshitagupta15june** [comment]
can u share more ss like how other news look and I think you can improve it further like reduce the legth of boxes and and more clear view with a light brown background

**Comment by raghav1482** [comment]
Light Brown background  on the body or on the news container?? @akshitagupta15june

**Comment by raghav1482** [comment]
> Light Brown background on the body or on the news container?? @akshitagupta15june

kindly clerify

**Pull request closed without merging**
