### PR TITLE
📚 Documentation: Updated Website Information

### LINKED ISSUE #1348: 🐛 Bug Report: Website Information not Updated
## 🐛 Bug description
`README.md` file not updated.

## It would be nice
If `README.md` file is updated. It would provide the latest information

## 👀 Have you spent some time to check if this issue has been raised before?
 - [x] I checked and didn't find similar issue

## 🏢 Have you read the Code of Conduct?
- [x] I have read the [Code of Conduct](https://github.com/akshitagupta15june/PetMe/blob/1a1d02723a1929da55e8684ddc4ff59eb13022da/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by nishitxmehta**
# What does this PR do?
This PR updates the latest images in `README.md` file.

Fixes #1348  

# Additional Information 
Hi @akshitagupta15june, If you consider this PR to get merged, please merge it.

### CODE REVIEW

**Review by Viveksati5143 — CHANGES_REQUESTED** [review]
Can you add ss of change?

**Comment by nishitxmehta** [comment]
I've updated the latest images in the `README.md` file.

**Comment by nishitxmehta** [comment]
I've updated the latest images in the `README.md` file.
Images can be seen here: https://github.com/akshitagupta15june/PetMe/pull/1349/files

**Comment by nishitxmehta** [comment]
Hi @akshitagupta15june, I've updated the latest images in the `README.md` file.
Images can be seen here: https://github.com/akshitagupta15june/PetMe/pull/1349/files

**Pull request closed without merging**
