### PR TITLE
added a read more button in news section

### PR DESCRIPTION
**Pull request by alwenpy**
Added a readmore button in news section to navigate it to the news link source.

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
add a ss

**Comment by alwenpy** [comment]
here is the Screenshot.
image

**Comment by alwenpy** [comment]
@akshitagupta15june please Review and merge PR

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
As news are already very short so i don't think read more is required

**Pull request closed without merging**
