### PR TITLE
Blog Submission Form

### PR DESCRIPTION
**Pull request by Pavan-Sai-padavala**
## Description

Added submission form to save blog data in the database

## Screenshots

image
image

- [ ] My code adheres to the established style guidelines of the project.
- [ ] I have included comments in areas that may be difficult to understand.
- [ ] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
Can u provide a video of showing where and how the data is stored

**Comment by Pavan-Sai-padavala** [comment]
I need Database url in "Pet Me-Backend" repository, to test the end-point to store form data.

Right now, I had built end-point to collect data, but need environment variables(Database URL) to test the end-point.

**Comment by akshitagupta15june** [comment]
ok comment me on discord and let me know I will work on it https://discord.gg/Q3MJHugPFh

**Review by 0rigin-c0de — APPROVED** [review]
Looks Good!

**Pull request closed without merging**
