### PR TITLE
Create abhishek.html

### PR DESCRIPTION
**Pull request by abhishek213-alb**
## Related Issue

Closes: #1319

## Description

Created a blog on dogs healthy life tips

## Screenshots
image
## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Review by Viveksati5143 — APPROVED** [review]

**Comment by abhishek213-alb** [comment]
@Viveksati5143 Please merge it too

**Review by Viveksati5143 — COMMENTED** [review]
@akshitagupta15june can do this

**Comment by abhishek213-alb** [comment]
@akshitagupta15june
Mam can you merge the pr

**Comment by abhishek213-alb** [comment]
@akshitagupta15june
Mam can you merge the pr

**Review by akshitagupta15june — APPROVED** [review]

**Pull request merged**
