### PR TITLE
fix navbar pet news visibilty

### LINKED ISSUE #1206: Pet News disappears from Navbar on some web pages
**Describe the bug**
Whenever you navigate to the Pet News or the support us section of the website, the Pet News link disappears from the Navbar.

**To Reproduce**
1. Click on the Pet News link on the navbar and see if you can still find it.

**Expected behavior**
Whenever you click on a Nav link, the nav link should still remain in the nav bar

**Screenshots**
The is the Home page and the Pet News Nav bar appears
Screenshot from 2023-10-13 12-33-54

This is the Support Us page where the Pet News link disappears

Screenshot from 2023-10-13 12-43-53

This is the Pet News page, the Pet News link also disappears

image

**Additional context**
This issue has been fixed by me and I have sent a pull request. Please add the hacktoberfest tag.

### PR DESCRIPTION
**Pull request by itz-salemm**
Pet News Visibility across all pages has been fixed
fixes #1206

### CODE REVIEW

**Comment by itz-salemm** [comment]
@akshitagupta15june please will this get merged

**Comment by akshitagupta15june** [comment]
Synk with change and add a ss

**Comment by itz-salemm** [comment]
@akshitagupta15june ready to be review and merged

**Comment by itz-salemm** [comment]
@akshitagupta15june Please add the hackoberfest-completed tag

**Pull request merged**
