### PR TITLE
Create footer!

### PR DESCRIPTION
**Pull request by abitsalihu**
Created footer with logo and 3 icons (only the github icon is active) for the main page!

Below is a picture of the footer:

Screen Shot 2022-09-23 at 19 57 16

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
Great work @abitsalihu 
Just waiting for PM @Susmita-Dey to review the pr, after that we will merge it!

@Susmita-Dey please review

**Review by akshitagupta15june — APPROVED** [review]

**Review by Susmita-Dey — APPROVED** [review]
LGTM. Good job. 👍

**Comment by Susmita-Dey** [comment]
But @akshitagupta15june if me merge this right now then it won't be counted in hacktoberfest I guess.

**Comment by akshitagupta15june** [comment]
yes it won't be counted but if the pr is aproved now, we should merge it ,so @abitsalihu good work

**Comment by akshitagupta15june** [comment]
Thanks for contributing ♡ @abitsalihu

**Comment by abitsalihu** [comment]
@akshitagupta15june , @Susmita-Dey - Thanks for having me. :)

**Pull request merged**
