### PR TITLE
Fix The Alignment In Cards

### PR DESCRIPTION
**Pull request by Mustafa-Azad025**
#46 Alignment Issue Fixed .

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
can you add the picture what changes you made
for verification before merging

**Comment by Mustafa-Azad025** [comment]
Please merge on 1 oct as hacktober fest will start

**Comment by Mustafa-Azad025** [comment]
I will again raise PR with Screen Short

**Comment by akshitagupta15june** [comment]
Try to go ve a new pr after oct 1

**Pull request closed without merging**
