### PR TITLE
changed the color of icons

### PR DESCRIPTION
**Pull request by yesimhozman**
image
The color of the two icons are changed from black to white. You can see it in the screenshot.

### CODE REVIEW

**Review by akshitagupta15june — APPROVED** [review]
Thanks for contributing 💜
Good work!
Have a look at issue #60 too

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
@yesimhozman can you look at the conflicting files issue

**Review by akshitagupta15june — APPROVED** [review]
Thanks for contributing.

**Comment by yesimhozman** [comment]
> Thanks for contributing.

You are welcome. I thought that "adopt me" button is not readable on hover. The text color could be black. What do you think ?
image

**Pull request merged**
