### PR TITLE
The help button exceeded the form. I fixed it using tailwind css.

### PR DESCRIPTION
**Pull request by bhargavshirin**
## Related Issue

Closes: #1506 

## Description

the position of the button was exceeding the form in reportstary.html. I changed it using tailwind.

## Screenshots

before 
Screenshot 2024-05-10 at 9 31 03 PM
 
after

Screenshot 2024-05-10 at 9 32 00 PM

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by bhargavshirin** [comment]
and could you please add label gssoc with level

**Comment by Swarnendu0123** [comment]
Attach the issue number in your description also give a title to your PR, it will helpful to evaluate your PR with the issue.

**Comment by bhargavshirin** [comment]
could you please add gssoc with level2 label

**Review by 0rigin-c0de — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
can u fetch and merge with current codebase so as to resolve conflicts

**Pull request closed without merging**
