### PR TITLE
Contact UI added

### PR DESCRIPTION
**Pull request by abhirup0199**
Screenshot 2024-05-21 143845 have created a new html and css file for contact ui. If you are satisfied with the design then add this to your main file. And I maintain the main theme of your website.

## Related Issue

#1531 

Closes: #issue_number

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Review by 0rigin-c0de — CHANGES_REQUESTED** [review]
Please provide Screenshot of the contact UI that you have changed

**Review by 0rigin-c0de — APPROVED** [review]

**Comment by abhirup0199** [comment]
Okay, I will change the background image.

**Comment by abhirup0199** [comment]
Screenshot 2024-05-29 065248
Check the new background image.

**Comment by akshitagupta15june** [comment]
can u provide a small video so i can see how it looks with complete website and try to checkout some different image that matched with petme background brown beige

**Comment by abhirup0199** [comment]
@akshitagupta15june mam, I was unable to find the main code of your contact ui. So, I created a different html and css file for that.

**Comment by abhirup0199** [comment]
@akshitagupta15june mam can you please assign this issue to me?

**Pull request closed without merging**
