### PR TITLE
Icon added in all pages

### PR DESCRIPTION
**Pull request by SrijaVuppala295**
## Related Issue

Closes: #1561

## Description

Added icon in all pages!!!
Even in everyblog i was made changes of icon..

## Screenshots

Screenshot 2024-05-18 021824
Screenshot 2024-05-18 021833
Screenshot 2024-05-18 021845
Screenshot 2024-05-18 021900
Screenshot 2024-05-18 021907
Screenshot 2024-05-18 021916

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by SrijaVuppala295** [comment]
@akshitagupta15june ,mam please review this, i am getting deployment failure .Everything is okay but still getting issue!!

**Review by 0rigin-c0de — APPROVED** [review]
Approved

**Comment by SrijaVuppala295** [comment]
@akshitagupta15june  please merge it , everything has been completed

**Comment by SrijaVuppala295** [comment]
@0rigin-c0de  @akshitagupta15june , please merge it !!

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
Great work!

**Pull request merged**
