### PR TITLE
Added donate in navbar

### PR DESCRIPTION
**Pull request by Anuragpal010104**
Changed to "Donate" to rehome Pet. Added a new page for Donating Money.

### CODE REVIEW

**Review by swethatheresa — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
which issues you are solving?

**Comment by Anuragpal010104** [comment]
> which issues you are solving?

To prevent potential misinterpretation, I modified the website's interface by replacing the "Donate" button with "Rehome Pet" to accurately convey the purpose of the action. Additionally, I introduced a "Donate" section within the "Support Us" dropdown to provide users with the option to contribute monetary support.

**Comment by Nayanika-12** [comment]
@akshitagupta15june Please assign me this issue I can work on it pretty easily.

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
remove this money.html please only donate changes acceptable

**Pull request closed without merging**
