### PR TITLE
Added the SOS button

### PR DESCRIPTION
**Pull request by yadavsairaj**
1. Added a SOS button
2.  The button when clicked redirects to sos report page.
3.  Button also has hover feature >> changes color  of button and font size and  increases the font weight.

image
image

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
Awesome work @yadavsairaj 
It is better if you give this pr after 1st oct to be counted in hacktoberfest

**Comment by yadavsairaj** [comment]
> Awesome work @yadavsairaj It is better if you give this pr after 1st oct to be counted in hacktoberfest

Yes it will be great. Do i have to submit PR again or you'll merge later in october. Thank you for this opportunity

**Comment by yadavsairaj** [comment]
I will reopen PR after 1st oct. 
Thank you

**Review by akshitagupta15june — APPROVED** [review]

**Review by akshitagupta15june — APPROVED** [review]
Great work!

**Comment by yadavsairaj** [comment]
Thankyou!

**Pull request merged**
