### PR TITLE
Added error msg in form fields in donate.html issue #1537

### PR DESCRIPTION
**Pull request by MaragathaMeenakshi**
## Related Issue

Closes: #1537

## Description
I have made changes in form input field in donote.html. In which user can notified by each step about the validation error and correct them.

## Screenshots

https://github.com/akshitagupta15june/PetMe/assets/113226919/a2388509-2227-4a67-bcf2-472bd1b092c8

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [ ] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Review by 0rigin-c0de — APPROVED** [review]
Good job

**Comment by MaragathaMeenakshi** [comment]
Could you add the label. @0rigin-c0de @akshitagupta15june

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
can u fetch and merge with current codebase, so as to resolve conflicts

**Comment by MaragathaMeenakshi** [comment]
I have resolved it. Kindly merge it. @akshitagupta15june

**Comment by MaragathaMeenakshi** [comment]
could you check my code . where I have implemented validation error . I think it is level2 
@akshitagupta15june

**Pull request merged**
