### PR TITLE
added petNews page

### PR DESCRIPTION
**Pull request by sanathan-git**

### CODE REVIEW

**Comment by sanathan-git** [comment]
Added pet News
Created new html page "news"
added tailwind styles
issue: #16

**Comment by Susmita-Dey** [comment]
Hello @sanathan-git Screenshots will be highly appreciated for the new features you have added.

**Comment by sanathan-git** [comment]
petNewss

**Review by akshitagupta15june — APPROVED** [review]
Thanks for contributing

**Pull request merged**
