### PR TITLE
Improved the smaller screens navbar UI

### LINKED ISSUE #543: Improve the UI of the navbar in smaller screens
**Is your feature request related to a problem? Please describe.**
The current UI of the navbar in smaller screens is not optimal and needs improvement. When viewing the website on mobile devices or smaller screens, the navbar doesn't provide a seamless and user-friendly experience. Users may encounter difficulties in navigating the website due to limited screen space and unresponsive design.

**Describe the solution you'd like**
I would like to enhance the UI of the navbar for smaller screens. The improved UI should address the following aspects:

Responsive Design: The navbar should adapt to different screen sizes, providing a consistent and user-friendly experience across mobile devices, tablets, and smaller desktop screens.
Compact Layout: On smaller screens, the navbar can take up a significant portion of the viewport, limiting the available space for content. The improved UI should consider a compact layout that takes up minimal vertical space, allowing users to view more of the main content.
Clear Navigation: The improved UI should ensure that navigation options are easily accessible and visually distinguishable, enabling users to quickly find and access different sections of the website.
Intuitive Mobile Navigation: Consider implementing a hamburger menu or similar mobile-friendly navigation pattern for screens with limited horizontal space. This will allow users to access the full navigation menu without cluttering the screen.

**Describe alternatives you've considered**
Some alternatives that can be considered are:

Stacked Navigation: Instead of a traditional horizontal navbar, a stacked navigation approach can be implemented for smaller screens. This involves placing the navigation options vertically, conserving horizontal space and providing easier touch targets for mobile users.
Off-canvas Menu: Another alternative is using an off-canvas menu that slides in from the side when activated, allowing users to access the full navigation options without occupying screen space continuously.

**Additional context**
image

@akshitagupta15june  Kindly assign me this issue as I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by mohammadshaad**
Fixes #543 

I have modified the navbar in smaller screens so that it looks good. 
Kindly review and merge the Pull Request.

### CODE REVIEW

**Comment by mohammadshaad** [comment]
@akshitagupta15june kindly review and merge the PR

**Review by akshitagupta15june — APPROVED** [review]

**Comment by mohammadshaad** [comment]
@akshitagupta15june please check now and also please please add the level tag also otherwise this contribution won't get counted for leadeboard

**Comment by mohammadshaad** [comment]
@akshitagupta15june kindly merge the PR

**Comment by mohammadshaad** [comment]
@swethatheresa kindly merge the PR

**Comment by mohammadshaad** [comment]
@akshaaatt kindly merge this PR

**Review by akshitagupta15june — APPROVED** [review]

**Pull request merged**
