### PR TITLE
Changed background image for better visibility

### PR DESCRIPTION
**Pull request by TilteD24**

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
Please add a screenshot

**Comment by TilteD24** [comment]
Screenshot

**Comment by TilteD24** [comment]
Ignore last commit I added screenshot in the repo

**Review by Susmita-Dey — APPROVED** [review]
LGTM

**Review by muditchoudhary — CHANGES_REQUESTED** [review]
I think the text Adopt Me is too small and does not look good on the left. How about If we center it and make it a little bigger

**Comment by TilteD24** [comment]
screenshot-2

**Comment by TilteD24** [comment]
screenshot-2

**Comment by TilteD24** [comment]
screenshot2

**Comment by muditchoudhary** [comment]
Could you also move give life to the needed animal sentence in the center?

**Review by muditchoudhary — APPROVED** [review]
yaa, this LGTM :rocket:

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
thanks for contributing
please look at issue #60

**Comment by TilteD24** [comment]
I forgot to push the last few changes in the positioning of the title. Should I create a new PR to update the branch? What should I do?

**Comment by muditchoudhary** [comment]
> I forgot to push the last few changes in the positioning of the title. Should I create a new PR to update the branch? What should I do?

No problem, you can open a new PR

**Pull request merged**
