### PR TITLE
Rework header with navbar, add menu toggle for mobile

### PR DESCRIPTION
**Pull request by Jokerko93**
I fixed whole header/navbar with how it displays at different resolutions. Added toggle menu for mobile/tablet screens.
375_nav
375_navHidden
648_nav
648_navHidden
1024_nav
fullNav

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
@Jokerko93 good work!
 there are some conflicting files as I have just now merged a request where someone has created the footer for the website, so can you remove your footer part and update your implementation with the current changes

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Please no the needful changes

**Comment by Jokerko93** [comment]
> Please no the needful changes

Should be fixed now. Let me know if anything else needs to be done. Hope you like it, it is my first PR. :)

**Review by akshitagupta15june — APPROVED** [review]
Good work @Jokerko93 
Thanks for contributing ♡

**Pull request merged**
