### PR TITLE
fixed pictures' background and added overflow hidden property

### PR DESCRIPTION
**Pull request by si88har1h**
image

### preview 
[changes](https://imgur.com/DJPU99M)

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
@Susmita-Dey kindly review

**Review by Susmita-Dey — CHANGES_REQUESTED** [review]
Make the logo color to white so that it's visible properly.

**Comment by si88har1h** [comment]
I have fetched and merged the previous changes. Apologies for this, I am new to open-source :)

**Comment by si88har1h** [comment]
image

Logos are now white

**Review by akshitagupta15june — APPROVED** [review]
Thanks for contributing 💜
Please look at issue #60 too

**Pull request merged**
