### PR TITLE
Fix the read button goes out it's parent block (#1562)

### PR DESCRIPTION
**Pull request by johnkim0306**
## Related Issue

Closes: #issue_number

issue number: (#1562)

## Description

Made a minimal changes ensuring read button is inside a parent block. 

## Screenshots

image

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Review by 0rigin-c0de — CHANGES_REQUESTED** [review]
Please add margin-bottom to fully separate the button from parent.

**Comment by johnkim0306** [comment]
image
Add margin bottom to fully separate the button from the parent class. @0rigin-c0de

**Review by 0rigin-c0de — APPROVED** [review]
Thanks

**Comment by johnkim0306** [comment]
@akshitagupta15june can you approve this and  close this issue please ?

**Pull request merged**
