### PR TITLE
auto collapse/ retreat navbar on window scroll

### PR DESCRIPTION
**Pull request by theanuragshukla**
added functionality to auto collapse/retreat navbar/header on scroll

### CODE REVIEW

**Comment by theanuragshukla** [comment]
@akshitagupta15june this commit added a great functionality to this website and improves the user experience by a great factor.

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
Please look at issue #60

**Comment by akshitagupta15june** [comment]
Thank you for your contribution

**Comment by theanuragshukla** [comment]
hey @akshitagupta15june , can you please add hacktoberfest-accepted label on this PR.

**Pull request merged**
