### PR TITLE
I have added two more news

### PR DESCRIPTION
**Pull request by rafiya2003**
issue #871 
I have added two more news

### CODE REVIEW

**Comment by rafiya2003** [comment]
what is the problem? can you plz tell me I have done the specified task.

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
good work! but make sure to always add a screenshot

**Comment by akshitagupta15june** [comment]
update your codebase with current code and please create a new pr because page UI is updated

**Comment by rafiya2003** [comment]
> good work! but make sure to always add a screenshot

sure

**Comment by rafiya2003** [comment]
> update your codebase with current code and please create a new pr because page UI is updated

here is a request . Since I'm a newbie I did not get the above sentence
I mean in what way you want me to update my codebase

**Comment by swethatheresa** [comment]
> > update your codebase with current code and please create a new pr because page UI is updated
> 
> here is a request . Since I'm a newbie I did not get the above sentence I mean in what way you want me to update my codebase

pull new changes

**Review by swethatheresa — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
please fetch and merge the changes and conflicts will be resolved

**Comment by akshitagupta15june** [comment]
please update codebase and also add a screenshot

**Pull request closed without merging**
