### PR TITLE
change in ui of the about box

### PR DESCRIPTION
**Pull request by tathagata2410**
## Related Issue

Closes: #issue_number

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by tathagata2410** [comment]
GsSOC'24 i have change the UI of the site and highlighted many unnoticed links like Report ,Adopts and all.

**Comment by tathagata2410** [comment]
i highlighted the Volunteer box

**Review by 0rigin-c0de — CHANGES_REQUESTED** [review]
Mention the issue that is being closed with this PR. Add a screenshot of what you did.

**Comment by tathagata2410** [comment]
i changed the ui of the about section,Highlihgted many important links
Screenshot (56)

**Pull request closed without merging**
