### PR TITLE
🐛 Bug Report: Resolved 'Theme Change' button

### LINKED ISSUE #1295: 🐛 Bug Report: Change Theme button not responding
### 🐛 Bug description
Theme change i.e. the `dark/light` button is not working.

Screen Recording

## It would be nice
If clicking on this button will set the theme change according to users choice.

## 👀 Have you spent some time to check if this issue has been raised before?
 - [x] I checked and didn't find similar issue

## 🏢 Have you read the Code of Conduct?
- [x] I have read the [Code of Conduct](https://github.com/akshitagupta15june/PetMe/blob/1a1d02723a1929da55e8684ddc4ff59eb13022da/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by nishitxmehta**
# What does this PR do?
This PR resolves the **Theme Change** button bug.

Screen Recording

Fixes #1295  

# Additional Information 
Hi @akshitagupta15june, If you consider this PR to get merged, please merge it.

### CODE REVIEW

**Comment by varundhand** [comment]
Good work @nishitxmehta

**Comment by PrajwalGraj** [comment]
Please add a demo video of it

**Comment by PrajwalGraj** [comment]
And also it has merge conflicts so please have a look at it and clear them

**Comment by Vidip-Ghosh** [comment]
Hey @nishitxmehta please synchronize your branch with the latest changes as the repo keeps on updating. 
1. Go to your forked repo. 
2. You will find the option of sync fork. 
3. Click on sync fork. 
4. In local, run git pull

**Comment by nishitxmehta** [comment]
Thanks, I was busy somewhere and will resolve in a short span of time.

**Comment by nishitxmehta** [comment]
@all, I've resolved the merge conflicts.

**Comment by nishitxmehta** [comment]
> Please add a demo video of it

Hi @PrajwalGraj, which demo video you're talking about?

**Comment by PrajwalGraj** [comment]
@nishitxmehta demo video in the sence, screenshot ya clips of the Modified working of the button which u changed now.

**Comment by nishitxmehta** [comment]
> @nishitxmehta demo video in the sence, screenshot ya clips of the Modified working of the button which u changed now.

I've added the video above. I'm attaching it here too.

Screen Recording

Fixes #1295

**Comment by akshitagupta15june** [comment]
please resolve conflict

**Comment by nishitxmehta** [comment]
Hi @akshitagupta15june, I've resolved the merge conflicts. Kindly merge it.

**Pull request merged**
