### PR TITLE
Fix adopt anchor tag in navbar for consistent styling in anchor tags

### PR DESCRIPTION
**Pull request by Sachin4219**
I created a issue (Small issue in responsive navbar #837) and this is the PR for the fix

### CODE REVIEW

**Review by swethatheresa — COMMENTED** [review]
post a screenshot

**Comment by Sachin4219** [comment]
image

**Comment by Sachin4219** [comment]
Sorry, the number of lines added and deleted looks high because of prettier extension i guess

**Comment by Sachin4219** [comment]
Hi, I submitted this pull request and it resolves the issue i created. Please merge it and close the PR

**Comment by akshitagupta15june** [comment]
Please update you codebase so conflict will be resolved

**Pull request closed without merging**
