### PR TITLE
fix text on dark mode so its easier to read

### PR DESCRIPTION
**Pull request by d3vsuthar**
this affects the following sections: about us, pet details

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
can u add a screenshot?

**Comment by d3vsuthar** [comment]
old on the left, new on the right
petme-css

**Comment by d3vsuthar** [comment]
old on the left, new on the right
petme-css

**Review by akshitagupta15june — APPROVED** [review]
Good work!
Thanks for contributing
please look at issue #60

**Pull request merged**
