### PR TITLE
News Section Updated

### PR DESCRIPTION
**Pull request by Hemant2335**
I have made some changes to the News Pet 

-> I have only made the structure with my own variables and values so if there is any backend part I can put those values as desired

-> Also this is completely responsive 

-> and if you want any other changes please let me know

Thank you 

Attchments

https://github.com/akshitagupta15june/PetMe/assets/85656999/4e09d93a-6679-41a4-9c05-b18863fc27ff

### CODE REVIEW

**Review by swethatheresa — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
please update your codebase with recent changes

**Comment by Hemant2335** [comment]
Now there is no conflict

**Comment by Hemant2335** [comment]
Mam please check and merge by Pr , also please add gssoc and level

**Comment by akshitagupta15june** [comment]
please update your codebase so conflicts will be resolved, always do a git pull before adding your changes

**Pull request closed without merging**
