### PR TITLE
Fixed Navbar in Mobile View

### PR DESCRIPTION
**Pull request by mritul**

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
Can u send a screenshot?

**Comment by akshitagupta15june** [comment]
Open the website in mobile and click on navbar

**Comment by mritul** [comment]
> Can u send a screenshot?

Yeah sure ! 

# Navbar Opened
<hr>

ss1

# Navbar Closed
<hr>

ss2

**Review by akshitagupta15june — APPROVED** [review]
Good work @mritul 
Have a look at issue #60

**Comment by mritul** [comment]
> Good work @mritul Have a look at issue #60

Thanks @akshitagupta15june ! Will take a look at issue #60

**Pull request merged**
