### PR TITLE
feat: add contributors section, Donate route and mobile menu

### PR DESCRIPTION
**Pull request by ramonbs**
I've added some new features that were already created:

- The donation form route has been added.
- The contributors section has been added to the main page.
- I made some alterations to the responsiveness, and it's not ideal yet, but much more fluid now.
- A mobile header menu has been added.

That's all for now. Thank you!

### CODE REVIEW

**Review by akshitagupta15june — APPROVED** [review]
Thankyou for contributing

**Comment by akshitagupta15june** [comment]
@ramonbs would u like to be a collaborator in this repo for reactdev?
Let me know I will send u a invite link to this repo

**Comment by ramonbs** [comment]
@akshitagupta15june Yes, I would like, please!  Thank you so much!!

**Comment by akshitagupta15june** [comment]
Ok I have added you as a collaborator please check your email

**Pull request merged**
