### PR TITLE
 Enhancing Contributors Section UX #364

### PR DESCRIPTION
**Pull request by Saurav-Pant**
issue- #364
 Implemented Option 1: GitHub icon now redirects to the contributor's page for seamless navigation and better engagement. Please review and provide feedback. Thank you!
screenshot

https://github.com/akshitagupta15june/PetMe/assets/103263909/8f83ed6a-b72d-4872-a379-1f15a0f0a951

### CODE REVIEW

**Review by swethatheresa — APPROVED** [review]

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
add a screenshot

**Review by swethatheresa — APPROVED** [review]

**Comment by Saurav-Pant** [comment]
https://github.com/akshitagupta15june/PetMe/assets/103263909/05320680-138c-4683-96ba-e2bd6b7983ce

**Review by akshitagupta15june — APPROVED** [review]
why the images are so big?

**Comment by akshitagupta15june** [comment]
please make the necessary changes

**Pull request closed without merging**
