### PR TITLE
Add a cool background related to pets in this website

### PR DESCRIPTION
**Pull request by anubhav047**

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
Can you add a image of what changes you made

**Comment by anubhav047** [comment]
https://user-images.githubusercontent.com/91625106/192300978-8bb0de4d-0105-4e82-b55f-faa0a06601b3.mov

Sure

**Comment by akshitagupta15june** [comment]
Hey great work @anubhav047 
According to me the background is kind of very dark
For a layman they have to kind of focus on what's actually on cards

Because right on your video my more focus is just on background cards visibility is very less

Can you work on it again please

**Comment by anubhav047** [comment]
https://user-images.githubusercontent.com/91625106/192317756-e12342bd-88e2-4e3f-a582-fe0928a22728.mov

Is it any better?

**Comment by akshitagupta15june** [comment]
Looks cool for now!
Thankyou so much for contributing @anubhav047

**Pull request merged**
