### PR TITLE
Add how to get started with open source in readme

### PR DESCRIPTION
**Pull request by ABHIGYAN-MOHANTA**
Hey! Made the pr based on issue no. #38 , please add the hacktoberfest-accepted label. And happy hacking!
Screenshot from 2022-09-30 18-02-37

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
Hey @ABHIGYAN-MOHANTA the pr looks good
Do you want it to merge now ?
It won't be counted in hacktoberfest

**Comment by akshitagupta15june** [comment]
Better is to close and give a new pr tomorrow

**Comment by ABHIGYAN-MOHANTA** [comment]
It has started, I think!
Screenshot from 2022-09-30 22-25-14

**Comment by ABHIGYAN-MOHANTA** [comment]
You can merge it now, if it doesn't get accepted. No worries.

**Review by akshitagupta15june — APPROVED** [review]
Good work @ABHIGYAN-MOHANTA

**Comment by ABHIGYAN-MOHANTA** [comment]
Thank you!

**Pull request merged**
