### PR TITLE
Donate Pet section created

### LINKED ISSUE #41: Add a backend to donate animal section
image

### PR DESCRIPTION
**Pull request by DugarRishab**
## Details

Related Issue: closes #41 
This is a REST API and the API can be accessed at `/api/v1` route. There are currently 8 endpoints: 

### Under Pet
| No | Route | Description |
| --- | --- | --- |
| 1. | `GET /api/v1/pet/`      |    Gives a list of all pets |
| 2. | `POST /api/v1/pet/`       |  To add another Pet |
| 3. | `GET /api/v1/pet/:id` |  To get details of only 1 pet |
| 4. | `DELETE /api/v1/pet/:id` |  To delete only 1 pet |

### Under Donation
| No | Route | Description |
| --- | --- | --- |
| 1. | `GET /api/v1/donation/`      |    Gives a list of all pets |
| 2. | `POST /api/v1/donation`       |  To add another Pet |
| 3. | `GET /api/v1/donation/:id` |  To get details of only 1 pet |
| 4. | `DELETE /api/v1/donation/:id` |  To delete only 1 pet |

## Request Body

The following details need to be given in the body of `POST` request for **PET**
- name
- breed (optional)
- color
- species
- gender
- location
- img (optional) (Not functional)

The following details need to be given in the body of `POST` request for **Donation**
- petName
- breed (optional)
- color
- species
- gender
- location
- img (optional) (Not functional)
- name
- address
- city
- state
- country
- email
- phone

***This API was made following the MVC architecture so it should be easily expandable.*** 

## How to Use? 

1. Install all the node modules: `npm i`
2. Create a env file (inside the server) called `config.env` and store all secrets in there. Template of this file is provided
3. Now `npm start` to start the server.

### CODE REVIEW

**Comment by DugarRishab** [comment]
Hey @muditchoudhary and @akshitagupta15june please check and review this PR

**Review by Susmita-Dey — APPROVED** [review]
LGTM.

**Review by muditchoudhary — APPROVED** [review]
@akshitagupta15june  For now, this looks good to me. @DugarRishab is it possible to test it? I don't know about the backend in js now. If it's possible to test locally, could you schedule a discord call with me so that we can test it out?

Thanks!

**Comment by DugarRishab** [comment]
> @akshitagupta15june For now, this looks good to me. @DugarRishab is it possible to test it? I don't know about the backend in js now. If it's possible to test locally, could you schedule a discord call with me so that we can test it out?
> 
> Thanks!

Yeah, it would be possible to test it locally. We can hop on discord tonight (8pm to 9pm or after 10pm IST).

**Comment by DugarRishab** [comment]
> > > @akshitagupta15june For now, this looks good to me. @DugarRishab is it possible to test it? I don't know about the backend in js now. If it's possible to test locally, could you schedule a discord call with me so that we can test it out?
> > > Thanks!
> > 
> > 
> > Yeah, it would be possible to test it locally. We can hop on discord tonight (8pm to 9pm or after 10pm IST).
> 
> Okay let's meet at 10 pm

How would you contact me? I am a discord noob.

**Comment by muditchoudhary** [comment]
> > > > @akshitagupta15june For now, this looks good to me. @DugarRishab is it possible to test it? I don't know about the backend in js now. If it's possible to test locally, could you schedule a discord call with me so that we can test it out?
> > > > Thanks!
> > > 
> > > 
> > > Yeah, it would be possible to test it locally. We can hop on discord tonight (8pm to 9pm or after 10pm IST).
> > 
> > 
> > Okay let's meet at 10 pm
> 
> How would you contact me? I am a discord noob.

Sorry, yesterday I could not contact you. What is your discord user name?

**Comment by DugarRishab** [comment]
> > > > > @akshitagupta15june For now, this looks good to me. @DugarRishab is it possible to test it? I don't know about the backend in js now. If it's possible to test locally, could you schedule a discord call with me so that we can test it out?
> > > > > Thanks!
> > > > 
> > > > 
> > > > Yeah, it would be possible to test it locally. We can hop on discord tonight (8pm to 9pm or after 10pm IST).
> > > 
> > > 
> > > Okay let's meet at 10 pm
> > 
> > 
> > How would you contact me? I am a discord noob.
> 
> Sorry, yesterday I could not contact you. What is your discord user name?

Here, Warman#4751

**Comment by DugarRishab** [comment]
> > > > > @akshitagupta15june For now, this looks good to me. @DugarRishab is it possible to test it? I don't know about the backend in js now. If it's possible to test locally, could you schedule a discord call with me so that we can test it out?
> > > > > Thanks!
> > > > 
> > > > 
> > > > Yeah, it would be possible to test it locally. We can hop on discord tonight (8pm to 9pm or after 10pm IST).
> > > 
> > > 
> > > Okay let's meet at 10 pm
> > 
> > 
> > How would you contact me? I am a discord noob.
> 
> Sorry, yesterday I could not contact you. What is your discord user name?

Please have postman installed. We will be using it.

**Comment by akshitagupta15june** [comment]
have you both had a discussion @muditchoudhary ?

**Review by akshaaatt — APPROVED** [review]

**Comment by muditchoudhary** [comment]
> have you both had a discussion @muditchoudhary ?

Yes @akshitagupta15june

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
thanks for contributing @DugarRishab

**Comment by DugarRishab** [comment]
> thanks for contributing @DugarRishab

✌️

**Pull request merged**
