### PR TITLE
Fixed Bug #1779

### PR DESCRIPTION
**Pull request by anuragkanojiya1**
## Related Issue

Closes: #1779 

## Description
Support Us section was not navigating to volunteer page in index page.

https://github.com/akshitagupta15june/PetMe/assets/144598258/2c038645-cb9e-4a5a-8d7f-0cee255a1d4d

## Video
After fixing the bug the Support Us section started working properly.

https://github.com/akshitagupta15june/PetMe/assets/144598258/4d0e9db6-fd33-4c04-98a6-bb0020d8209b

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Review by akshitagupta15june — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
fetch and merge to resolve conflicts

**Comment by anuragkanojiya1** [comment]
> fetch and merge to resolve conflicts

@akshitagupta15june 
fetch and merge is done.
Kindly accept this pull request.

**Comment by anuragkanojiya1** [comment]
@akshitagupta15june Fetch and merge is done.
Kindly merge my pull request.

**Comment by akshitagupta15june** [comment]
its not resolved, please fetch and merge again

**Comment by anuragkanojiya1** [comment]
@akshitagupta15june check now

**Pull request merged**
