### PR TITLE
Designed volunteer.html page

### PR DESCRIPTION
**Pull request by anurag-4508**
Thanks for reviewing my contribution

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
Can u give a screenshot of your page

**Comment by anurag-4508** [comment]
Sure, this is the screenshot of volunteer page 

screencapture

**Comment by Anuran12** [comment]
A mobile view too please

**Comment by muditchoudhary** [comment]
Looks good to me? Share the mobile version screenshot too if you have made it

**Review by Susmita-Dey — APPROVED** [review]
LGTM

**Review by akshitagupta15june — APPROVED** [review]

**Pull request merged**
