### PR TITLE
fixed[584] bug fixed size of light mood icon

### PR DESCRIPTION
**Pull request by mohitparmar1**
Screenshot (48)

### CODE REVIEW

**Comment by mohitparmar1** [comment]
@akshitagupta15june hey! review please

**Review by swethatheresa — APPROVED** [review]

**Comment by akshitagupta15june** [comment]
mention issue that u are targetting

**Comment by mohitparmar1** [comment]
ISSUE

MOON ICON GET BIGGER ND THAT MAKE WEBSITE ALIGNMENT UGLY

**Comment by mohitparmar1** [comment]
@akshitagupta15june review issue #584 and if it is relevant then merge this.

**Review by akshitagupta15june — APPROVED** [review]

**Pull request merged**
