### PR TITLE
[FEATURE]: "In the SOS report section, I improved the appearance by modifying the tailwind CSS styles of the section."

### PR DESCRIPTION
**Pull request by sakeel-103**
#1880  Solved.

"In the SOS report section, I improved the appearance by modifying the CSS styles of the section."

#1880 Solved.
@akshitagupta15june 
Please consider this PR and merge it.
And also, I apologize for this PR as I am doing without being assigned.

Closes: #1880 

## Description
"In the SOS report section, I improved the appearance by modifying the CSS styles of the section".
I added tailwind CSS in section class also improved the CSS of the SOS report section. 

## Screenshots

video -

https://github.com/akshitagupta15june/PetMe/assets/136844498/8c77733e-7582-4478-a8f7-72b0f11140d0

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by sakeel-103** [comment]
@akshitagupta15june 
Here in this PR, why all checks showing failed.

**Comment by akshitagupta15june** [comment]
created pr without being assigned an issue is not allowed.

**Comment by sakeel-103** [comment]
But please at least check the given issue number, that was raised by me itself. I had done the PR of my raised issue that is #1880.
Please at least check this issue number.

**Comment by sakeel-103** [comment]
But I mentioned the issue number, at least check the issue number

**Pull request closed without merging**
