### PR TITLE
revamped footer

### PR DESCRIPTION
**Pull request by d3vsuthar**
top: new
bottom: old
footer-md

Issue #106 

Changes: 
- Changed colors to match the theme
- Fixed responsiveness on all screens
- SVG icons (from earlier PR)
- Cleaned up email subscription block (removed text 'enter your email address' - was redundant)
- Logo now links to the website

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
Footer should have this colour only other than this looks good
Can u change the background colour to previous one

**Review by d3vsuthar — COMMENTED** [review]
footer color reverted to bg-gray-900

**Comment by akshitagupta15june** [comment]
Please share sc

**Comment by akshitagupta15june** [comment]
Screenshot

**Comment by d3vsuthar** [comment]
here you go
image

**Review by akshitagupta15june — APPROVED** [review]
Good work
Thanks for contributing 💜
Please look at this issue too #60

**Pull request merged**
