### PR TITLE
Resolve #63 By Adding Newsletter Subscription

### LINKED ISSUE #63: Add a "Subscribe to newsletter" option in the footer of website
For example

image

### PR DESCRIPTION
**Pull request by Ahnaf-codes**
# Change Log

  -  Added Newsletter subscription to footer
  -  Added my handle to contributors.md

# Request to Maintainer

  - Please accept it for Hacktoberfest2022.
  - Thanks for letting me work on your repo.

### CODE REVIEW

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
can u add a screenshot of the changes u made

**Comment by Ahnaf-codes** [comment]
Screenshot 2022-10-01 at 00-24-05 PetMe

**Review by akshitagupta15june — APPROVED** [review]
Good work!

**Comment by akshitagupta15june** [comment]
can you resolve the conflicts by fetching and merging the recent updated code?

**Review by akshitagupta15june — CHANGES_REQUESTED** [review]
can you resolve the conflicts by fetching and merging the recent updated code?
there are conflicting files

**Comment by Ahnaf-codes** [comment]
Done

**Review by akshitagupta15june — APPROVED** [review]
Great work @Ahnaf-codes

**Comment by prashant-jadu** [comment]
Can you please assign this issue to me?

**Comment by Ahnaf-codes** [comment]
@prashant-jadu This a merged or not an issue

**Comment by prashant-jadu** [comment]
ok assign this to me.

**Pull request merged**
