### PR TITLE
Fixed navbar hover colors and interactivity of logo and theme toggler

### PR DESCRIPTION
**Pull request by marsian83**
All navbar buttons now react to hover and change color according to their theme in index.html
Also, theme toggles now feels more interactive as the cursor changes to a pointer instead of being static
Logo also grows on hover and cursor chagnes to pointer instead of text cursor.

### CODE REVIEW

**Comment by akshitagupta15june** [comment]
Can you add some screenshot to your implementation

**Comment by marsian83** [comment]
Screenshot (6)
Screenshot (7)
Screenshot (8)

The color on light theme for the logo has also become dark according to the theme
Plus added these changes to navbars across the html files

**Review by akshitagupta15june — APPROVED** [review]
Well done

**Comment by akshitagupta15june** [comment]
Please look at issue #60 too

**Pull request merged**
